FROM ubuntu
RUN apt-get update
RUN apt -y install build-essential
RUN apt-get -y install gcc-multilib g++-multilib
#RUN apt-get -y install libc6-dev-i386
COPY sp3.cpp .
RUN g++ -m32 -masm=intel sp3.cpp -o lab3 -g -lstdc++
CMD ./lab3
